[metadata]
name = "current_file"
description = "Fuzzy search lines in a single file with line highlight"
requirements = ["bat", "nl"]  # nl for line numbering

[source]
command = "nl -ba -s ':' current_file.txt"  # Replace 'current_file.txt' with your file; or use a shell variable like $FILE

[preview]
command = "bat --color=always --highlight-line {split:::0} current_file.txt"  # Replace with your file
offset = "{split:::0}"  # Extracts line number for highlighting

[display]
template = "{split:::1}"  # Shows only the line text for fuzzy matching

[output]
template = "{split:::0}"  # Outputs the line number on selection

[ui]
preview_panel = { "size" = 70, "scrollbar" = true }
